import '9. Exceptions.dart';

void main() {
  funWithExceptions();
}
